services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: library-backend

    env_file:
      - .env

    ports:
      - "${APP_PORT}:8081"

    volumes:
      - ./backend:/app

    working_dir: /app

    command: air -c .air.toml

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: library-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "1433:1433"
    volumes:
      - library_sqlserver_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  library_sqlserver_data: